### ISSUE TITLE
Getting index handle seems broken

### ISSUE THREAD

**Issue by enderger** [idanarye/bevy-yoleck#33]
Currently, if you load the level index like shown in the docs.rs example, it seems as though the `level_index_assets.get` method breaks.
Loading this plugin panics with "Failed to load level" when in the `Loading` state
```rust
// SYSTEMS
pub fn load_level(
    level_index_assets: Res<Assets<YoleckLevelIndex>>, 
    asset_server: Res<AssetServer>,
    mut yoleck_loading_cmd: ResMut<YoleckLoadingCommand>,
    current_level: Res<CurrentLevel>,
    mut state: ResMut<NextState<GameState>>,
) {
    if let Some(level) = current_level.0 {
        bevy::log::debug!("LOADING LEVEL: {level}");
        let level_index_handle: Handle<YoleckLevelIndex> = asset_server.load("levels/index.yoli");
        let Some(level_index) = level_index_assets.get(&level_index_handle) else { panic!("Failed to load level") };

        let level_handle: Handle<YoleckRawLevel> = asset_server.load(
            format!("levels/{}", level_index[level].filename)
        );
        *yoleck_loading_cmd = YoleckLoadingCommand::FromAsset(level_handle);
        state.set(GameState::InGame);
    }
}

// PLUGIN
pub struct Plugin;

impl bevy::app::Plugin for Plugin {
    fn build(&self, app: &mut App) {
        app
            .insert_resource(CurrentLevel(Some(1)))
            .add_systems(OnEnter(GameState::Loading), load_level);
    }
}
```

**Comment by idanarye** [comment]
I think this is just how Bevy assets works. `asset_server.load()` is asynchronous - the asset is not loaded when it this method returns. It only starts to load, and there is no guarantee when it's going to be finished. This is why you have to try to get it from the assets every frame, and if you fail - don't `panic!`, just try again on the next frame. Maybe it'll be loaded by then.

I do admit, though, that the example I gave in the docs is flawed. It would have worked in Bevy 0.11 and its flickery asset loading/unloading mechanism, but Bevy 0.12 has a more stable asset lifetime management (not sure if it's part of Assets v2 or just a regular improvement), which sadly means we cannot rely on the asset to flicker into being loaded. In Bevy 0.12, once the system exists and `level_index_handle` is dropped the asset is immediately released - which means we won't get it in the next frame.

The solution is to store it in a resource. A local resource would suffice. I'll update the example.
