### ISSUE TITLE
Gui not visible unless bevy_egui is explicitly added to Cargo.toml

### ISSUE THREAD

**Issue by jeffw387** [idanarye/bevy-yoleck#39]
As the title says. It could be some problem with the way my project is structured (maybe a conflicting crate?) but I just wanted to put it out there in case anyone is having the same issue. For me, explicitly adding 'bevy_egui = "0.26.0"' to the Cargo.toml fixes the issue.

**Comment by idanarye** [comment]
Okay. I think I know the problem. That's what I get for using the minimal possible set of features:

```toml
bevy_egui = { version = "^0.26", default-features = false, features = ["default_fonts"] }
```

Without the `render` feature, it won't render the egui. When you add it manually it gets added with all the default features - including `render`.

I'll add that feature.
